sudo: false
language: python
compiler:
 - gcc
 - clang
addons:
  apt:
    packages:
      - libjansson-dev
before_install:
 - git clean -x -f
 - ./autogen.sh
script:
 - ./configure
 - make -j4
 - make check -j4
 - cd pysearpc && python test_pysearpc.py
notifications:
    email: false
